spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: toma